spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mode
    username: test
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: true
logging:
  level:
    org.hibernate:
      type.descriptor.sql: DEBUG
      SQL: DEBUG
